### ISSUE TITLE
Add a more neutral option

### ISSUE THREAD

**Issue by mabouchacra** [Zenika/humeur-du-mois#167]
Currently we have three choices :

- Great
- Not that great
- Not great at all

I feel like the first option is positive while the two others are negative. Is it possible to add (or modify the second option) a label *OK* or *Normal* ?

**Comment by david-dasilva** [comment]
How about adding more options that could be combined? ex : 

- Great :smile: 
- Exhausted :weary: 
- Stressed :scream: 
- Under pressure :hot_face: 
- Excited :grinning:

**Comment by hgwood** [comment]
I like the idea @david-dasilva, but that's a deeper change. We could even imagine having both the general feeling and a few secondary feelings. I'll create an issue.

There seem to be a consensus on adding a fourth option, so we'll do that.
