### ISSUE TITLE
Allow the user to vote directly in the mail

### ISSUE THREAD

**Issue by Ked57** [Zenika/humeur-du-mois#70]
As someone pointed me out today, people used to be able to click and vote directly into the mail. He would then be redirected to the confirmation page

**Comment by EmmanuelDemey** [comment]
We can maybe use GMAIL Actions ? 
https://developers.google.com/gmail/markup/overview#gmail_actions

**Comment by Ked57** [comment]
Nice! didn't know about those

**Comment by patou** [comment]
Or, we can use AMP Email : https://developers.google.com/gmail/ampemail/
